language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - npm install -g npm@^2
install:
  - npm install
script:
  - npm test
  - npm run build
branches:
  only:
    - master
    - dev